// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnZUvGqpvEE_orX620P_9I2h28swGKDbs',
    appId: '1:755210924592:web:64cdeee31cef8061c1f3f5',
    messagingSenderId: '755210924592',
    projectId: 'learn-work-9bbf7',
    authDomain: 'learn-work-9bbf7.firebaseapp.com',
    storageBucket: 'learn-work-9bbf7.firebasestorage.app',
    measurementId: 'G-J6LFNBLB4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVjVOriDE6vQrSz-yImZK2uIyl4PyrSV8',
    appId: '1:755210924592:android:62598f2e443c7486c1f3f5',
    messagingSenderId: '755210924592',
    projectId: 'learn-work-9bbf7',
    storageBucket: 'learn-work-9bbf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Fq15mLci3FT2Y-pmHEW3mXDSA6jg9d4',
    appId: '1:755210924592:ios:6637b7b3e28ed895c1f3f5',
    messagingSenderId: '755210924592',
    projectId: 'learn-work-9bbf7',
    storageBucket: 'learn-work-9bbf7.firebasestorage.app',
    androidClientId: '755210924592-d7ohs9qetavdg15dmbeghesqup789enh.apps.googleusercontent.com',
    iosClientId: '755210924592-brobjeb2ir2085786brdg6abovuerbr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnWork.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Fq15mLci3FT2Y-pmHEW3mXDSA6jg9d4',
    appId: '1:755210924592:ios:f144bcfe58af3a76c1f3f5',
    messagingSenderId: '755210924592',
    projectId: 'learn-work-9bbf7',
    storageBucket: 'learn-work-9bbf7.firebasestorage.app',
    iosBundleId: 'com.example.learnWork',
  );
}